---
bibliography: references.bib
---

# El Método de Componentes Demográficos por Cohortes (MCDC)

Uno de los métodos más ampliamente utilizados, —desde los años cincuenta— para realizar estimaciones y proyecciones de la población, por sexo y edad, es el Método de Componentes Demográficos por Cohortes (MCDC). Dicho método se ha venido aplicando típicamente para grupos de edad de cinco años y períodos de estimación-proyección de cinco años (5x5). No obstante, dada la mejora de las fuentes de información y las necesidades de focalización de la política pública, se ha optado por emplear el MCDC por edad individual y año calendario (1x1). De esta manera, se ha constatado que las estimaciones y proyecciones de población 1x1 permiten hacer un seguimiento más preciso de la evolución de las cohortes en cada año.

El MCDC estima y proyecta la población por sexo y edad, incorporando la evolución de los tres componentes determinantes de la dinámica poblacional: mortalidad, fecundidad y migración. Para ello, se utiliza la ecuación compensadora para cada sexo y edad.

$$
N^{t+1}=N^t+B^{t, t+1}-D^{t, t+1}+I^{t+1}-E^{t+1} 
$$

donde:

$N^t$ = la población inicial estimada al 1 de enero;

$N^{t+1}$ = la población estimada por el modelo al 1 de enero en $t+1$;

$B^{t, t+1}$ = los nacimientos de mujeres en edad fértil, ocurridos en el año;

$D^{t, t+1}$ = las defunciones ocurridas a lo largo del período $t, t+1$;

$I^{t+1}$ y $E^{t+1}$ = el total de inmigrantes y de emigrantes, respectivamente, al final del período $t+1$.

Para la aplicación del método, se requieren los siguientes insumos: la población inicial desglosada por sexo y edad, la relación de supervivencia desglosada por sexo y edad, las tasas específicas de fecundidad por edad y el saldo migratorio internacional desglosado por sexo y edad.  Es importante destacar que todos estos insumos deben estar disponibles por año calendario.

Para la determinación de dichos insumos, es necesario establecer las tendencias históricas de los tres componentes demográficos mediante procedimientos de estimación.
