# Introduccción {.unnumbered}

Desde su establecimiento en 1957, el Centro Latinoamericano y Caribeño de Demografía (CELADE) —actualmente conocido como CELADE - División de Población de la CEPAL— ha desempeñado un papel fundamental para la región en temas de capacitación en análisis demográfico; desarrollo y avances metodológicos en estimaciones y proyecciones de población; así como en materia de difusión de sus contribuciones. A lo largo de su trayectoria, el CELADE ha publicado diversos informes y herramientas que han aportado en la construcción del conocimiento demográfico de los países de América Latina y el Caribe (ALC).

En 1968, el CELADE inició la serie de Boletines Demográficos, los cuales brindaron información sobre estimaciones y proyecciones elaboradas en Latinoamérica a través del Método de Componentes Demográficos por Cohortes (MCDC). En la actualidad, esta serie ha sido reemplazada por el Observatorio Demográfico, publicación anual que sigue siendo una referencia importante para el análisis de la dinámica demográfica de los países de la región. Entre sus publicaciones destacadas también se encuentra la compilación "Métodos para Proyecciones Demográficas" de 1984, que recopila los principales métodos utilizados —entonces— por el CELADE para la elaboración de proyecciones poblacionales.

Con la expansión del uso de los microcomputadores en los años 80, el CELADE promovió la aplicación de los métodos de proyección a través de programas informáticos. El PRODEM fue el primer software demográfico ampliamente utilizado; en su segunda versión de 1991, ofrecía un conjunto de métodos demográficos y matemáticos para la elaboración de proyecciones de población nacionales y subnacionales, que insumían datos en edades quinquenales y años terminados en 0 y 5. En este contexto, se destaca la creación de PRODEX —en 2009— una herramienta que combinaba las funcionalidades del PRODEM con la interfaz de las hojas de cálculo de Excel, herramienta de uso más generalizado. Además de su interfaz más sencilla, el programa permitía realizar proyecciones por año calendario y edades simples, lo cual representó un avance significativo en la región.

En línea con el compromiso de difundir y facilitar el acceso a los métodos de proyección y sus aplicaciones, el presente manual tiene como objetivo socializar las actualizaciones de los métodos de estimación y proyección utilizados en ALC por el CELADE. De la misma manera, se presentan ejemplos de la implementación de todo el proceso en el lenguaje de programación de código abierto `R Project` con un enfoque en el análisis demográfico. Aunque el uso de `R Project` tiene una curva de aprendizaje pronunciada en comparación con el software comercial, ofrece ventajas en términos de velocidad y capacidad de procesamiento de grandes volúmenes de datos. Además, permite la fácil implementación de métodos que requieren un mayor esfuerzo y complejidad computacional.

Con el objetivo de mantener la accesibilidad para todos los usuarios, en este manual también se proporciona plantillas de Excel para la aplicación de los métodos, siempre que es posible. De esta manera, se ofrece una variedad de herramientas flexibles y adaptadas a diferentes niveles de habilidad y recursos disponibles.
